# Generated by Django 4.2.21 on 2025-11-26 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('cars', '0001_initial'),
        ('activities', '0001_initial'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('promotion_type', models.IntegerField(choices=[(1, 'Chỗ ở'), (2, 'Chuyến bay'), (3, 'Hoạt động'), (4, 'Xe')], default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_promotions', to='promotions.promotion')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='FlightPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='flights.flight')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_promotions', to='promotions.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='CarPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='cars.car')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_promotions', to='promotions.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activity_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='activities.activitydate')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_promotions', to='promotions.promotion')),
            ],
        ),
    ]
