# Generated by Django 4.2.21 on 2025-10-13 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('promotion_type', models.IntegerField(choices=[(1, 'Chỗ ở'), (2, 'Chuyến bay'), (3, 'Hoạt động')], default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='hotels.hotel')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_promotions', to='promotions.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='FlightPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='airports.airport')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_promotions', to='promotions.promotion')),
            ],
        ),
    ]
