# Generated by Django 4.2.21 on 2025-12-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
