# Generated by Django 4.2.21 on 2025-11-02 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_flightpromotion_custom_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightpromotion',
            name='custom_end_date',
        ),
        migrations.RemoveField(
            model_name='flightpromotion',
            name='custom_start_date',
        ),
        migrations.RemoveField(
            model_name='hotelpromotion',
            name='custom_end_date',
        ),
        migrations.RemoveField(
            model_name='hotelpromotion',
            name='custom_start_date',
        ),
    ]
