# Generated by Django 4.2.21 on 2025-12-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_activitypromotion_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypromotion',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='activitypromotion',
            name='discount_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='carpromotion',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='carpromotion',
            name='discount_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='flightpromotion',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='flightpromotion',
            name='discount_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='roompromotion',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='roompromotion',
            name='discount_percent',
            field=models.FloatField(default=0.0),
        ),
    ]
