# Generated by Django 4.2.21 on 2025-12-05 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotions', '0004_alter_activitypromotion_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='marketing_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to=settings.AUTH_USER_MODEL),
        ),
    ]
