# Generated by Django 4.2.21 on 2025-12-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_promotion_marketing_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='marketing_manager',
        ),
    ]
