# Generated by Django 4.2.21 on 2025-10-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
