# Generated by Django 4.2.21 on 2025-10-31 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0002_roombookingdetail_owner_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombookingdetail',
            name='owner_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
