# Generated by Django 4.2.21 on 2025-11-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roombookingdetail_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombookingdetail',
            name='room_count',
            field=models.PositiveIntegerField(default=1, help_text='Số lượng phòng đặt'),
        ),
        migrations.AddField(
            model_name='roombookingdetail',
            name='room_type',
            field=models.CharField(blank=True, help_text='Loại phòng (copy từ Room)', max_length=100, null=True),
        ),
    ]
