# Generated by Django 4.2.21 on 2025-11-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_roombookingdetail_owner_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombookingdetail',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='roombookingdetail',
            name='check_out',
            field=models.DateTimeField(),
        ),
    ]
