# Generated by Django 4.2.21 on 2025-11-28 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_created_at_room_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomamenity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomamenity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roomamenity',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
