# Generated by Django 4.2.21 on 2025-12-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roomamenity_created_at_roomamenity_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombookingdetail',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
