# Generated by Django 4.2.21 on 2025-12-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_roombookingdetail_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='dayuse_duration_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='price_per_day',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='room',
            name='stay_type',
            field=models.CharField(choices=[('overnight', 'Overnight'), ('dayuse', 'Day Use')], default='overnight', max_length=50),
        ),
    ]
