# Generated by Django 4.2.21 on 2026-01-09 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_room_dayuse_duration_hours_room_price_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Phòng có thể được đặt (không bị khóa / bảo trì)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_rooms', to='rooms.room')),
            ],
        ),
        migrations.AddField(
            model_name='roombookingdetail',
            name='physical_rooms',
            field=models.ManyToManyField(blank=True, help_text='Danh sách phòng cụ thể (101, 102, ...) được gán cho booking', related_name='room_booking_details', to='rooms.physicalroom'),
        ),
    ]
