# Generated by Django 4.2.21 on 2025-10-17 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('journey', 'Journey'), ('moving', 'Moving'), ('experience', 'Experience'), ('food', 'Food'), ('tourist_attractions', 'Tourist_Attractions'), ('travel_preparation', 'Travel_Preparation')], default='journey', max_length=255)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('more_information', models.TextField(blank=True, null=True)),
                ('cancellation_policy', models.TextField(blank=True, null=True)),
                ('departure_information', models.TextField(blank=True, null=True)),
                ('avg_price', models.FloatField(default=0.0)),
                ('avg_star', models.FloatField(default=0.0)),
                ('total_time', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cities.city')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_adult', models.FloatField(default=0.0)),
                ('price_child', models.FloatField(default=0.0)),
                ('adult_quantity', models.PositiveIntegerField(default=1)),
                ('child_quantity', models.PositiveIntegerField(default=1)),
                ('date_launch', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_packages', to='activities.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activities.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDateBookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_adult', models.FloatField(default=0.0)),
                ('price_child', models.FloatField(default=0.0)),
                ('adult_quantity_booking', models.PositiveIntegerField(default=1)),
                ('child_quantity_booking', models.PositiveIntegerField(default=1)),
                ('date_launch', models.DateTimeField()),
                ('activity_package_name', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_image', models.CharField(blank=True, max_length=255, null=True)),
                ('avg_price', models.FloatField(default=0.0)),
                ('avg_star', models.FloatField(default=0.0)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_dates', to='activities.activitydate')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_date_detail', to='bookings.booking')),
            ],
        ),
        migrations.AddField(
            model_name='activitydate',
            name='activity_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_dates', to='activities.activitypackage'),
        ),
    ]
