# Generated by Django 4.2.21 on 2025-11-26 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('cities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('journey', 'Journey'), ('moving', 'Moving'), ('experience', 'Experience'), ('food', 'Food'), ('tourist_attractions', 'Tourist_Attractions'), ('travel_preparation', 'Travel_Preparation')], default='journey', max_length=255)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('more_information', models.TextField(blank=True, null=True)),
                ('cancellation_policy', models.TextField(blank=True, null=True)),
                ('departure_information', models.TextField(blank=True, null=True)),
                ('avg_price', models.FloatField(default=0.0)),
                ('avg_star', models.FloatField(default=0.0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('total_time', models.PositiveIntegerField()),
                ('total_click', models.PositiveIntegerField(default=0)),
                ('total_positive', models.PositiveIntegerField(default=0)),
                ('total_negative', models.PositiveIntegerField(default=0)),
                ('total_neutral', models.PositiveIntegerField(default=0)),
                ('total_weighted_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cities.city')),
                ('event_organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_adult', models.FloatField(default=0.0)),
                ('price_child', models.FloatField(default=0.0)),
                ('adult_quantity', models.PositiveIntegerField(default=1)),
                ('child_quantity', models.PositiveIntegerField(default=1)),
                ('date_launch', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_packages', to='activities.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activities.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDateBookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_adult', models.FloatField(default=0.0)),
                ('price_child', models.FloatField(default=0.0)),
                ('adult_quantity_booking', models.PositiveIntegerField(default=1)),
                ('child_quantity_booking', models.PositiveIntegerField(default=1)),
                ('date_launch', models.DateTimeField()),
                ('activity_package_name', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_image', models.CharField(blank=True, max_length=255, null=True)),
                ('avg_price', models.FloatField(default=0.0)),
                ('avg_star', models.FloatField(default=0.0)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('final_price', models.FloatField(default=0.0)),
                ('activity_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_dates_bookings', to='activities.activitydate')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_date_detail', to='bookings.booking')),
                ('event_organizer_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_dates_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activitydate',
            name='activity_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_dates', to='activities.activitypackage'),
        ),
        migrations.CreateModel(
            name='UserActivityInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('positive_count', models.PositiveIntegerField(default=0)),
                ('negative_count', models.PositiveIntegerField(default=0)),
                ('neutral_count', models.PositiveIntegerField(default=0)),
                ('weighted_score', models.FloatField(default=0.0)),
                ('last_interacted', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activity_interactions', to='activities.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activity_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
