# Generated by Django 4.2.21 on 2025-10-13 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_service_type'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDateBookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_adult', models.FloatField(default=0.0)),
                ('price_child', models.FloatField(default=0.0)),
                ('adult_quantity_booking', models.PositiveIntegerField(default=1)),
                ('child_quantity_booking', models.PositiveIntegerField(default=1)),
                ('date_launch', models.DateTimeField()),
                ('total_price', models.FloatField(default=0.0)),
                ('activity_package_name', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_image', models.CharField(blank=True, max_length=255, null=True)),
                ('avg_price', models.FloatField(default=0.0)),
                ('avg_star', models.FloatField(default=0.0)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_dates', to='activities.activitydate')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_date_detail', to='bookings.booking')),
            ],
        ),
    ]
