# Generated by Django 4.2.21 on 2025-11-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydatebookingdetail',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='activitydatebookingdetail',
            name='final_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='activitydatebookingdetail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
