# Generated by Django 4.2.21 on 2026-01-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitydate',
            name='adult_quantity',
        ),
        migrations.RemoveField(
            model_name='activitydate',
            name='child_quantity',
        ),
        migrations.AddField(
            model_name='activitydate',
            name='max_participants',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
