# Generated by Django 4.2.21 on 2025-09-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('journey', 'Journey'), ('moving', 'Moving'), ('experience', 'Experience'), ('food', 'Food'), ('tourist_attractions', 'Tourist_Attractions'), ('travel_preparation', 'Travel_Preparation')], default='journey', max_length=255),
        ),
    ]
