# Generated by Django 4.2.21 on 2025-10-18 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydatebookingdetail',
            name='activity_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_dates_bookings', to='activities.activitydate'),
        ),
    ]
