# Generated by Django 4.2.21 on 2026-01-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_remove_activitydate_adult_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydate',
            name='participants_available',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
