# Generated by Django 4.2.21 on 2025-10-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activitydatebookingdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitydatebookingdetail',
            name='total_price',
        ),
    ]
