# Generated by Django 4.2.21 on 2025-10-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activitydatebookingdetail_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
