# Generated by Django 4.2.21 on 2025-09-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitydate',
            name='name',
        ),
    ]
