# Generated by Django 4.2.21 on 2025-09-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activitydate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydate',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
