# Generated by Django 4.2.21 on 2025-10-26 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_review_count'),
        ('activities', '0003_remove_activitydatebookingdetail_total_price'),
    ]

    operations = [
    ]
