# Generated by Django 4.2.21 on 2025-10-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activitydate_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitydate',
            name='price',
        ),
        migrations.AddField(
            model_name='activitydate',
            name='adult_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activitydate',
            name='child_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activitydate',
            name='price_adult',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='activitydate',
            name='price_child',
            field=models.FloatField(default=0.0),
        ),
    ]
