# Generated by Django 4.2.21 on 2025-10-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_remove_activitydate_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='departure_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
