# Generated by Django 4.2.21 on 2025-10-30 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0007_activity_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydatebookingdetail',
            name='event_organizer_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_dates_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
