# Generated by Django 4.2.25 on 2025-11-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activitydatebookingdetail_total_price'),
        ('activities', '0008_activitydatebookingdetail_event_organizer_activity'),
    ]

    operations = [
    ]
