# Generated by Django 4.2.25 on 2025-11-02 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0009_merge_20251101_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydatebookingdetail',
            name='event_organizer_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_dates_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitydatebookingdetail',
            name='activity_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_dates_bookings', to='activities.activitydate'),
        ),
    ]
