# Generated by Django 4.2.21 on 2025-11-26 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('nearbyLocation', models.TextField(blank=True, null=True)),
                ('mostFeature', models.TextField(blank=True, null=True)),
                ('facilities', models.TextField(blank=True, null=True)),
                ('withUs', models.TextField(blank=True, null=True)),
                ('usefulInformation', models.TextField(blank=True, null=True)),
                ('amenitiesAndFacilities', models.TextField(blank=True, null=True)),
                ('locationInfo', models.TextField(blank=True, null=True)),
                ('regulation', models.TextField(blank=True)),
                ('avg_star', models.FloatField(default=0.0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_click', models.PositiveIntegerField(default=0)),
                ('total_positive', models.PositiveIntegerField(default=0)),
                ('total_negative', models.PositiveIntegerField(default=0)),
                ('total_neutral', models.PositiveIntegerField(default=0)),
                ('total_weighted_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='cities.city')),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='UserHotelInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('positive_count', models.PositiveIntegerField(default=0)),
                ('negative_count', models.PositiveIntegerField(default=0)),
                ('neutral_count', models.PositiveIntegerField(default=0)),
                ('weighted_score', models.FloatField(default=0.0)),
                ('last_interacted', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hotel_interactions', to='hotels.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hotel_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hotel')},
            },
        ),
    ]
