# Generated by Django 4.2.21 on 2025-10-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
