# Generated by Django 4.2.21 on 2025-08-18 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='large_description',
        ),
    ]
