# Generated by Django 4.2.21 on 2025-12-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='best_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
