# Generated by Django 4.2.21 on 2025-08-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_hotel_large_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
