# Generated by Django 4.2.21 on 2025-10-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='total_click',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='total_negative',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='total_neutral',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='total_positive',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
