# Generated by Django 4.2.21 on 2025-08-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotelimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='locationInfo',
        ),
        migrations.AddField(
            model_name='hotel',
            name='mostFeature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='nearbyLocation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='usefulInformation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='withUs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
