# Generated by Django 4.2.21 on 2025-10-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_total_click_hotel_total_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='weighted_score',
            field=models.FloatField(default=0.0),
        ),
    ]
