# Generated by Django 4.2.21 on 2025-12-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_best_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='min_price',
            field=models.FloatField(default=0.0),
        ),
    ]
