# Generated by Django 4.2.21 on 2025-08-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_remove_hotel_locationinfo_hotel_mostfeature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='short_description',
        ),
    ]
