# Generated by Django 4.2.21 on 2025-08-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_remove_hotel_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='locationInfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
