# Generated by Django 4.2.21 on 2025-11-03 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_rename_weighted_score_hotel_total_weighted_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='point',
        ),
    ]
