# Generated by Django 4.2.25 on 2025-11-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_add_discount_and_search_history'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersearchhistory',
            new_name='hotels_user_user_id_675f24_idx',
            old_name='hotels_user_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='usersearchhistory',
            new_name='hotels_user_session_1c40e5_idx',
            old_name='hotels_user_session_idx',
        ),
    ]
