# Generated by Django 4.2.21 on 2025-10-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_alter_hotel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
