# Generated by Django 4.2.21 on 2025-12-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('staff', 'Staff'), ('driver', 'Driver'), ('owner', 'Owner'), ('event_organizer', 'Event Organizer'), ('marketing_manager', 'Marketing Manager'), ('flight_operations_staff', 'Flight Operations Staff'), ('airline_ticketing_staff', 'Airline Ticketing Staff')], default='customer', max_length=255),
        ),
    ]
