# Generated by Django 4.2.21 on 2025-10-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_manage_customuser_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('staff', 'Staff'), ('driver', 'Driver'), ('owner', 'Owner'), ('event_organizer', 'Event Organizer')], default='customer', max_length=255),
        ),
    ]
