# Generated by Django 4.2.21 on 2025-12-05 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_owner'),
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_staffs', to='hotels.hotel'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_staffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('hotel_staff', 'Hotel Staff'), ('driver', 'Driver'), ('owner', 'Owner'), ('event_organizer', 'Event Organizer'), ('marketing_manager', 'Marketing Manager'), ('flight_operations_staff', 'Flight Operations Staff'), ('airline_ticketing_staff', 'Airline Ticketing Staff')], default='customer', max_length=255),
        ),
    ]
