# Generated by Django 4.2.21 on 2025-12-06 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_hotel_alter_customuser_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='flight_operation_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_staffs', to=settings.AUTH_USER_MODEL),
        ),
    ]
