# Generated by Django 4.2.21 on 2025-12-06 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0002_airline_flight_operations_staff'),
        ('accounts', '0005_customuser_flight_operation_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_staffs', to='airlines.airline'),
        ),
    ]
