# Generated by Django 4.2.21 on 2025-10-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('staff', 'Staff'), ('driver', 'Driver'), ('owner', 'Owner')], default='customer', max_length=10),
        ),
    ]
