# Generated by Django 4.2.21 on 2025-12-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_airline'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='driver_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('busy', 'Busy')], default='idle', max_length=6),
        ),
    ]
