# Generated by Django 4.2.21 on 2025-10-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hotel',
        ),
    ]
