# Generated by Django 4.2.21 on 2025-12-28 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('accounts', '0007_customuser_driver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='driver_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='cities.city'),
        ),
    ]
