# Generated by Django 4.2.21 on 2026-01-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_driver_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chatbot_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
