# Generated by Django 4.2.21 on 2026-01-06 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_chatbot_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='chatbot_id',
            new_name='chat_id',
        ),
    ]
