# Generated by Django 4.2.21 on 2025-08-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
