# Generated by Django 4.2.21 on 2025-11-26 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airports', '0001_initial'),
        ('bookings', '0001_initial'),
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_duration', models.IntegerField(default=0, help_text='Tổng thời gian (phút)')),
                ('baggage_included', models.BooleanField(default=False)),
                ('stops', models.IntegerField(default=0)),
                ('base_price', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='airlines.aircraft')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlines.airline')),
            ],
        ),
        migrations.CreateModel(
            name='SeatClassPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_class', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First Class')], max_length=20)),
                ('multiplier', models.FloatField(default=1.0)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('has_meal', models.BooleanField(default=False)),
                ('has_free_drink', models.BooleanField(default=False)),
                ('has_lounge_access', models.BooleanField(default=False)),
                ('has_power_outlet', models.BooleanField(default=False)),
                ('has_priority_boarding', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_classes', to='flights.flight')),
            ],
        ),
        migrations.CreateModel(
            name='FlightLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('flight_code', models.CharField(max_length=20)),
                ('duration_minutes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='airports.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='airports.airport')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='flights.flight')),
            ],
        ),
        migrations.CreateModel(
            name='FlightBookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_class', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First Class')], default='economy', max_length=20)),
                ('num_passengers', models.IntegerField()),
                ('total_price', models.FloatField(default=0.0)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('final_price', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_details', to='bookings.booking')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flights.flight')),
            ],
        ),
    ]
