# Generated by Django 4.2.21 on 2025-10-12 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightbookingdetail',
            name='departure_datetime',
        ),
    ]
