# Generated by Django 4.2.21 on 2025-11-26 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='flightbookingdetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flightbookingdetail',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='flightleg',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flightleg',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='seatclasspricing',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='seatclasspricing',
            name='updated_at',
        ),
    ]
