# Generated by Django 4.2.21 on 2025-11-16 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0002_aircraft'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightleg',
            name='aircraft',
        ),
        migrations.RemoveField(
            model_name='flightleg',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='flightleg',
            name='cabin_class',
        ),
        migrations.RemoveField(
            model_name='flightleg',
            name='has_free_drink',
        ),
        migrations.RemoveField(
            model_name='flightleg',
            name='has_free_snack',
        ),
        migrations.RemoveField(
            model_name='flightleg',
            name='has_power_outlet',
        ),
        migrations.AddField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='airlines.aircraft'),
        ),
        migrations.AddField(
            model_name='flight',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='SeatClassPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_class', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First Class')], max_length=20)),
                ('multiplier', models.FloatField(default=1.0)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('has_meal', models.BooleanField(default=False)),
                ('has_free_drink', models.BooleanField(default=False)),
                ('has_lounge_access', models.BooleanField(default=False)),
                ('has_power_outlet', models.BooleanField(default=False)),
                ('has_priority_boarding', models.BooleanField(default=False)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_classes', to='flights.flight')),
            ],
        ),
    ]
