# Generated by Django 4.2.21 on 2026-01-09 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_created_at_flight_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbookingdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='FlightSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_class', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First Class')], default='economy', max_length=20)),
                ('seat_number', models.CharField(max_length=10)),
                ('is_available', models.BooleanField(default=True, help_text='Ghế còn trống để book hay đã được giữ chỗ / sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.flight')),
            ],
            options={
                'unique_together': {('flight', 'seat_number')},
            },
        ),
        migrations.AddField(
            model_name='flightbookingdetail',
            name='seats',
            field=models.ManyToManyField(blank=True, help_text='Các ghế cụ thể (12A, 12B, ...) đã được gán cho booking', related_name='flight_bookings', to='flights.flightseat'),
        ),
    ]
