# Generated by Django 4.2.21 on 2025-10-21 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='service_ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='service_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Hotel'), (2, 'Car'), (3, 'Flight'), (4, 'Activity')], null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'service_type', 'service_ref_id')},
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='hotel',
        ),
    ]
