# Generated by Django 4.2.21 on 2025-10-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='review',
            name='point',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
