# Generated by Django 4.2.21 on 2025-10-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_confidence_review_point_review_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='point',
        ),
    ]
