# Generated by Django 4.2.21 on 2025-11-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_remove_review_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='service_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Hotel'), (2, 'Car'), (3, 'Flight'), (4, 'Activity'), (5, 'Handbook')], null=True),
        ),
    ]
