# Generated by Django 4.2.21 on 2025-11-16 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='VD: Boeing 777, Airbus A321', max_length=100)),
                ('registration_number', models.CharField(help_text='Số đăng ký máy bay (VD: VN-A123)', max_length=50, unique=True)),
                ('total_seats', models.IntegerField(default=0)),
                ('economy_seats', models.IntegerField(default=0)),
                ('business_seats', models.IntegerField(default=0)),
                ('first_class_seats', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('manufacture_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircrafts', to='airlines.airline')),
            ],
            options={
                'verbose_name': 'Aircraft',
                'verbose_name_plural': 'Aircrafts',
                'ordering': ['airline', 'model'],
            },
        ),
    ]
