# Generated by Django 4.2.21 on 2025-12-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0002_airline_flight_operations_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='code',
            field=models.CharField(help_text='Mã IATA (VD: VN, VJ)', max_length=255, unique=True),
        ),
    ]
