# Generated by Django 4.2.21 on 2025-11-26 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Handbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('cuisine', 'Cuisine'), ('activity', 'Activity'), ('day_trip', 'Day Trip'), ('night_life', 'Night Life'), ('scenic_spots', 'Scenic Spots'), ('trip', 'Trip'), ('best_hotel', 'Best Hotel'), ('shopping', 'Shopping'), ('holidays_and_events', 'Holidays And Events'), ('accommodation', 'Accommodation'), ('airport', 'Airport'), ('travel_information', 'Travel Information')], default='cuisine', max_length=255)),
                ('avg_star', models.FloatField(default=0.0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('total_click', models.PositiveIntegerField(default=0)),
                ('total_positive', models.PositiveIntegerField(default=0)),
                ('total_negative', models.PositiveIntegerField(default=0)),
                ('total_neutral', models.PositiveIntegerField(default=0)),
                ('total_weighted_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handbooks', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='cities.city')),
            ],
        ),
        migrations.CreateModel(
            name='UserHandbookInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('positive_count', models.PositiveIntegerField(default=0)),
                ('negative_count', models.PositiveIntegerField(default=0)),
                ('neutral_count', models.PositiveIntegerField(default=0)),
                ('weighted_score', models.FloatField(default=0.0)),
                ('last_interacted', models.DateTimeField(auto_now=True)),
                ('handbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_handbook_interactions', to='handbooks.handbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_handbook_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'handbook')},
            },
        ),
    ]
