# Generated by Django 4.2.21 on 2025-11-11 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0002_city_image_handbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('total_click', models.PositiveIntegerField(default=0)),
                ('total_positive', models.PositiveIntegerField(default=0)),
                ('total_negative', models.PositiveIntegerField(default=0)),
                ('total_neutral', models.PositiveIntegerField(default=0)),
                ('total_weighted_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='cities.city')),
            ],
        ),
    ]
