# Generated by Django 4.2.21 on 2025-11-11 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handbooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHandbookInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('positive_count', models.PositiveIntegerField(default=0)),
                ('negative_count', models.PositiveIntegerField(default=0)),
                ('neutral_count', models.PositiveIntegerField(default=0)),
                ('weighted_score', models.FloatField(default=0.0)),
                ('last_interacted', models.DateTimeField(auto_now=True)),
                ('handbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_handbook_interactions', to='handbooks.handbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_handbook_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'handbook')},
            },
        ),
    ]
