# Generated by Django 4.2.21 on 2025-11-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0002_userhandbookinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbook',
            name='category',
            field=models.CharField(choices=[('cuisine', 'Cuisine'), ('activity', 'Activity'), ('day_trip', 'Day Trip'), ('night_life', 'Night Life'), ('scenic_spots', 'Scenic Spots'), ('trip', 'Trip'), ('best_hotel', 'Best Hotel'), ('shopping', 'Shopping'), ('holidays_and_events', 'Holidays And Events'), ('accommodation', 'Accommodation'), ('airport', 'Airport'), ('travel_information', 'Travel Information')], default='cuisine', max_length=255),
        ),
    ]
