# Generated by Django 4.2.21 on 2025-11-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0003_handbook_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbook',
            name='avg_star',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='handbook',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
