# Generated by Django 4.2.21 on 2025-11-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0004_handbook_avg_star_handbook_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbook',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
