# Generated by Django 4.2.21 on 2025-11-14 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handbooks', '0005_alter_handbook_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbook',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handbooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
