# Generated by Django 4.2.21 on 2025-11-26 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField()),
                ('luggage', models.PositiveIntegerField(null=True)),
                ('avg_star', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_speed', models.FloatField(default=0.0)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('total_booking_count', models.PositiveIntegerField(default=0)),
                ('total_weighted_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(blank=True, max_length=255, null=True)),
                ('dropoff_location', models.CharField(blank=True, max_length=255, null=True)),
                ('lat1', models.FloatField(blank=True, null=True)),
                ('lng1', models.FloatField(blank=True, null=True)),
                ('lat2', models.FloatField(blank=True, null=True)),
                ('lng2', models.FloatField(blank=True, null=True)),
                ('pickup_datetime', models.DateTimeField()),
                ('driver_required', models.BooleanField(default=True)),
                ('distance_km', models.FloatField(default=0.0)),
                ('total_time_estimate', models.FloatField(default=0.0)),
                ('passenger_quantity_booking', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('final_price', models.FloatField(default=0.0)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_detail', to='bookings.booking')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_bookings', to='cars.car')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCarInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_count', models.PositiveIntegerField(default=0)),
                ('weighted_score', models.FloatField(default=0.0)),
                ('last_interacted', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_car_interactions', to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_car_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'car')},
            },
        ),
    ]
