# Generated by Django 4.2.21 on 2025-10-13 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField()),
                ('luggage', models.PositiveIntegerField(null=True)),
                ('point', models.FloatField(default=0.0)),
                ('avg_star', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_speed', models.FloatField(default=0.0)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarBookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('pickup_datetime', models.DateTimeField()),
                ('driver_required', models.BooleanField(default=False)),
                ('distance_km', models.FloatField(default=0.0)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_detail', to='bookings.booking')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
    ]