# Generated by Django 4.2.21 on 2025-11-27 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbookingdetail',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='carbookingdetail',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='carbookingdetail',
            name='total_price',
        ),
    ]
