# Generated by Django 4.2.21 on 2025-10-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbookingdetail',
            name='lat1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbookingdetail',
            name='lat2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbookingdetail',
            name='lng1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbookingdetail',
            name='lng2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbookingdetail',
            name='passenger_quantity_booking',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='carbookingdetail',
            name='total_time_estimate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='carbookingdetail',
            name='driver_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='carbookingdetail',
            name='dropoff_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carbookingdetail',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
