# Generated by Django 4.2.21 on 2025-09-24 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='star',
            new_name='avg_star',
        ),
    ]
