# Generated by Django 4.2.21 on 2025-11-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_carbookingdetail_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbookingdetail',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='carbookingdetail',
            name='final_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='carbookingdetail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
