# Generated by Django 4.2.21 on 2025-10-18 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carbookingdetail_lat1_carbookingdetail_lat2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbookingdetail',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_bookings', to='cars.car'),
        ),
    ]
