# Generated by Django 4.2.21 on 2025-09-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_star_car_avg_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='luggage',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
