# Generated by Django 4.2.21 on 2025-09-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_luggage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='avg_speed',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
