# Generated by Django 4.2.21 on 2025-10-30 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0003_alter_carbookingdetail_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbookingdetail',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
