# Generated by Django 4.2.21 on 2025-12-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carbookingdetail_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbookingdetail',
            name='status',
            field=models.CharField(choices=[(0, 'Starting'), (1, 'Picked'), (2, 'Moving'), (3, 'Arrived')], default=0, max_length=20),
        ),
    ]
