# Generated by Django 4.2.21 on 2025-12-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carbookingdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbookingdetail',
            name='dropoff_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carbookingdetail',
            name='pickup_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
