# Generated by Django 4.2.21 on 2025-11-03 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0004_carbookingdetail_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='total_booking_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='total_weighted_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='UserCarInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_count', models.PositiveIntegerField(default=0)),
                ('weighted_score', models.FloatField(default=0.0)),
                ('last_interacted', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_car_interactions', to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_car_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'car')},
            },
        ),
    ]
