# Generated by Django 4.2.21 on 2025-09-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_avg_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='avg_speed',
            field=models.FloatField(default=0.0),
        ),
    ]
