# Generated by Django 4.2.21 on 2025-12-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carbookingdetail_dropoff_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_per_km',
            field=models.FloatField(default=0.0),
        ),
    ]
