# Generated by Django 4.2.21 on 2025-11-03 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_total_booking_count_car_total_weighted_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='point',
        ),
    ]
