# Generated by Django 4.2.21 on 2025-12-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_price_per_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='avg_star',
            field=models.FloatField(default=0.0),
        ),
    ]
