# Generated by Django 4.2.21 on 2025-09-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
