# Generated by Django 4.2.21 on 2025-10-28 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='cities.city'),
        ),
    ]
