# Generated by Django 4.2.21 on 2025-11-26 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.PositiveSmallIntegerField(choices=[(1, 'Hotel'), (2, 'Car'), (3, 'Flight'), (4, 'Activity'), (5, 'Handbook')])),
                ('service_ref_ids', models.JSONField(blank=True, default=list, help_text='Danh sách id chi tiết dịch vụ', null=True)),
                ('booking_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Cancelled'), (4, 'Completed')], default=1)),
                ('payment_status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Success'), (3, 'Failed'), (4, 'Cancelled'), (5, 'Unpaid'), (6, 'Paid'), (7, 'Refunded')], default=1)),
                ('total_price', models.FloatField(default=0.0)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('final_price', models.FloatField(default=0.0)),
                ('refund_amount', models.FloatField(blank=True, default=0.0, help_text='Số tiền đã hoàn lại', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RefundPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.PositiveSmallIntegerField(choices=[(1, 'Hotel'), (2, 'Car'), (3, 'Flight'), (4, 'Activity'), (5, 'Handbook')])),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('policy_type', models.IntegerField(choices=[(1, 'Hoàn tiền 100%'), (2, 'Hoàn tiền một phần'), (3, 'Không hoàn tiền')], default=1)),
                ('refund_percentage', models.FloatField(blank=True, help_text='Phần trăm hoàn tiền (0-100)', null=True)),
                ('refund_amount', models.FloatField(blank=True, help_text='Số tiền hoàn cố định', null=True)),
                ('hours_before_start', models.IntegerField(blank=True, help_text='Số giờ trước khi bắt đầu để áp dụng policy này', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_info', to='bookings.booking')),
            ],
        ),
    ]
