# Generated by Django 4.2.21 on 2025-11-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.PositiveSmallIntegerField(choices=[(1, 'Hotel'), (2, 'Car'), (3, 'Flight'), (4, 'Activity'), (5, 'Handbook')])),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('policy_type', models.IntegerField(choices=[(1, 'Hoàn tiền 100%'), (2, 'Hoàn tiền một phần'), (3, 'Không hoàn tiền')], default=1)),
                ('refund_percentage', models.FloatField(blank=True, help_text='Phần trăm hoàn tiền (0-100)', null=True)),
                ('refund_amount', models.FloatField(blank=True, help_text='Số tiền hoàn cố định', null=True)),
                ('hours_before_start', models.IntegerField(blank=True, help_text='Số giờ trước khi bắt đầu để áp dụng policy này', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.FloatField(blank=True, default=0.0, help_text='Số tiền đã hoàn lại', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Success'), (3, 'Failed'), (4, 'Cancelled'), (5, 'Unpaid'), (6, 'Paid'), (7, 'Refunded')], default=1),
        ),
    ]
