# Generated by Django 4.2.21 on 2026-01-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Success'), (3, 'Failed'), (4, 'Cancelled'), (5, 'Unpaid'), (6, 'Paid'), (7, 'Refunded'), (8, 'Rebooked')], default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Cancelled'), (4, 'Completed'), (5, 'Rebooked')], default=1),
        ),
    ]
