# Generated by Django 4.2.21 on 2025-10-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Hotel'), (2, 'Car'), (3, 'Flight'), (4, 'Activity')]),
        ),
    ]
