# Generated by Django 4.2.21 on 2025-11-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Hotel'), (2, 'Car'), (3, 'Flight'), (4, 'Activity'), (5, 'Handbook')]),
        ),
    ]
