# Generated by Django 4.2.21 on 2025-10-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
