# Generated by Django 4.2.21 on 2025-10-26 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_total_price'),
        ('bookings', '0003_alter_booking_service_ref_id'),
    ]

    operations = [
    ]
