# Generated by Django 4.2.21 on 2025-11-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_link_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
    ]
