# Generated by Django 4.2.21 on 2025-11-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_is_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
